// Generated by Healix QA contracts. Do not edit by hand.
import { test, expect } from '@playwright/test';

function extractRows(body: unknown): any[] {
  if (Array.isArray(body)) return body as any[];
  if (body && typeof body === 'object') {
    const record = body as Record<string, unknown>;
    for (const key of ['items', 'data', 'results', 'rows', 'content']) {
      if (Array.isArray(record[key])) return record[key] as any[];
    }
  }
  return [];
}

function buildUrl(pathname: string, params: Record<string, string | number | boolean | null | undefined> = {}): string {
  const [pathOnly, existingQuery = ''] = String(pathname).split('?');
  const search = new URLSearchParams(existingQuery);
  for (const [key, value] of Object.entries(params)) {
    if (value !== null && value !== undefined) search.set(key, String(value));
  }
  const query = search.toString();
  return query ? pathOnly + '?' + query : pathOnly;
}

function sampleValueForField(name: string, index = 0): unknown {
  const lower = name.toLowerCase();
  if (lower.includes('email')) return 'healix-' + Date.now() + '-' + index + '@example.test';
  if (lower.includes('password')) return 'HealixPass123!';
  if (lower.includes('price') || lower.includes('amount') || lower.includes('count') || lower.endsWith('id')) return index + 1;
  if (lower.includes('date')) return new Date().toISOString();
  if (lower.includes('status')) return 'open';
  if (lower.includes('priority')) return 'high';
  if (lower.includes('role')) return 'member';
  return 'healix-' + name + '-' + Date.now() + '-' + index;
}

function buildPayload(fields: string[], overrides: Record<string, unknown> = {}): Record<string, unknown> {
  const payload: Record<string, unknown> = {};
  fields.forEach((field, index) => {
    payload[field] = Object.prototype.hasOwnProperty.call(overrides, field)
      ? overrides[field]
      : sampleValueForField(field, index);
  });
  return payload;
}

function pathNeedsSample(pathname: string): boolean {
  return /(?:\{[^}]+\}|:[A-Za-z_][\w-]*)/.test(pathname);
}

function fillDynamicPath(pathname: string, value: string | number): string {
  return pathname
    .replace(/\{[^}]+\}/, encodeURIComponent(String(value)))
    .replace(/:[A-Za-z_][\w-]*/, encodeURIComponent(String(value)));
}

function collectionPathForDynamic(pathname: string): string {
  const normalized = String(pathname);
  if (/^\/api\/comments\/issue\/[:{]/.test(normalized)) return '/api/issues';
  return pathname
    .replace(/(?:\/\{[^}]+\}|\/:[A-Za-z_][\w-]*)(?:\/.*)?$/, '') || '/';
}

function sampleIdFromRows(rows: any[]): string | number | null {
  for (const row of rows) {
    if (!row || typeof row !== 'object') continue;
    for (const key of ['id', '_id', 'uuid', 'slug', 'issueId', 'projectSlug']) {
      const value = row[key];
      if (value !== undefined && value !== null && String(value).length > 0) return value as string | number;
    }
  }
  return null;
}

async function resolveApiPathFromRequest(request: any, pathname: string): Promise<string | null> {
  if (!pathNeedsSample(pathname)) return pathname;
  const collectionPath = collectionPathForDynamic(pathname);
  const response = await request.get(collectionPath);
  if (!response.ok()) return null;
  const rows = extractRows(await response.json());
  const sample = sampleIdFromRows(rows);
  return sample === null ? null : fillDynamicPath(pathname, sample);
}

async function resolveApiPathFromPage(page: any, pathname: string): Promise<string | null> {
  if (!pathNeedsSample(pathname)) return pathname;
  const collectionPath = collectionPathForDynamic(pathname);
  const result = await page.evaluate(async ({ path }) => {
    const response = await fetch(path, { credentials: 'include' });
    let body: unknown = null;
    try { body = await response.json(); } catch {}
    return { ok: response.ok, body };
  }, { path: collectionPath });
  if (!result.ok) return null;
  const sample = sampleIdFromRows(extractRows(result.body));
  return sample === null ? null : fillDynamicPath(pathname, sample);
}

async function apiFetchFromPage(page: any, path: string, options: { method?: string; body?: unknown } = {}) {
  return page.evaluate(async ({ path: innerPath, options: innerOptions }) => {
    const response = await fetch(innerPath, {
      method: innerOptions.method || 'GET',
      headers: innerOptions.body === undefined ? undefined : { 'Content-Type': 'application/json' },
      body: innerOptions.body === undefined ? undefined : JSON.stringify(innerOptions.body),
      credentials: 'include',
    });
    let text = '';
    try { text = await response.text(); } catch {}
    return { status: response.status, ok: response.ok, text: text.slice(0, 500) };
  }, { path, options });
}

test.describe('Healix QA filter contracts', () => {
  test('[QAC:qac-filter-get-api-cards-status] [CAT:api_contract] GET /api/cards enforces status filter', async ({ request }) => {
    // [SRC:src/server.js] Source maps query param "status" to response field "status".
    const listResponse = await request.get("/api/cards");
    expect(listResponse.ok(), 'unfiltered list endpoint should be reachable').toBeTruthy();
    const listRows = extractRows(await listResponse.json());
    const sample = listRows.find((row) => row && row["status"] !== undefined && row["status"] !== null && String(row["status"]).length > 0);
    test.skip(!sample, 'No live sample row exposes status; cannot exercise filter contract deterministically.');
    const value = String(sample["status"]);
    const filteredPath = buildUrl("/api/cards", { "status": value });
    const filteredResponse = await request.get(filteredPath);
    expect(filteredResponse.ok(), 'filtered endpoint should be reachable').toBeTruthy();
    const filteredRows = extractRows(await filteredResponse.json());
    expect(filteredRows.length, 'filtering by an existing value should return at least one row').toBeGreaterThan(0);
    for (const row of filteredRows) {
      expect(String(row["status"]), `row must satisfy status=${value}`).toBe(value);
    }
  });
});






