'use strict';

/**
 * G54: Self-review Claude pass.
 *
 * After the write pass produces Playwright specs, fork ONE extra
 * `claude --print` invocation per shard with a Haiku model + low effort.
 * The reviewer reads each generated spec alongside its `[SRC:*]`
 * citations and flags specs whose assertions don't match the cited
 * source (a class of contract-drift bug that static rules like G47 can't
 * detect — e.g. asserting status 404 when the controller actually
 * returns 401).
 *
 * MVP policy: this pass FLAGS / QUARANTINES specs the reviewer marks
 * high-severity. We deliberately do NOT auto-patch — patch-application
 * is error-prone enough that letting the spec fail in execution
 * (where G56 then routes the verdict correctly) is the safer default.
 *
 * Default: OFF. Enable with HEALIX_CLAUDE_SELF_REVIEW=on. Cost: one
 * Haiku call per shard (~$0.02 each).
 *
 * Target-agnostic: the reviewer prompt names no target project.
 */

const fs = require('node:fs');
const path = require('node:path');

const Logger = require('../../logger');
const { spawnClaude } = require('./exec');

const SPEC_FILE_RE = /\.spec\.(ts|tsx|js|jsx|mjs|cjs)$/i;

// Cap to keep the prompt below Claude's input limits.
const MAX_SPECS_PER_REVIEW = 8;
const MAX_SPEC_BYTES = 8_000;
const MAX_SRC_BYTES = 4_000;

const REVIEW_SYSTEM_PROMPT = `You are reviewing Playwright specs generated by an automated QA pipeline.
For each spec given, check whether its assertions match the cited [SRC:*] source files.
Output ONLY a JSON array (no prose, no markdown fences). Each item:
  { "file": "<spec basename>", "severity": "low" | "med" | "high", "issue": "<one-sentence reason>" }
Include a row only when there IS an issue. severity "high" means the spec will reliably fail or
asserts something the source contradicts. severity "med" means the assertion is loose/weakly-grounded.
severity "low" means style/comment-only nit. Output [] if everything is fine.`;

/**
 * Public API.
 *
 * @param {object} args
 * @param {string} args.projectPath
 * @param {string} args.generatedDir   default: `${projectPath}/tests/generated`
 * @param {string} args.runId
 * @param {string} [args.binary]       claude CLI binary (default 'claude')
 * @param {string} [args.model]        model id (default haiku for cheap pass)
 * @returns {Promise<{
 *   ran: boolean,
 *   flagged: Array<{file:string, severity:string, issue:string}>,
 *   quarantined: Array<{file:string, severity:string, issue:string}>,
 *   reason?: string,
 * }>}
 */
async function runSelfReviewPass({ projectPath, generatedDir, runId, binary = 'claude', model, fallbackUsed = false } = {}) {
  // G60: invert the default. Pre-G60 the gate was opt-in (`=on` required);
  // dominant `ungrounded_text` failure mode was untouched. Now opt-out
  // (`=off` disables); cost is +$0.10/run for one Haiku call.
  const envFlag = String(process.env.HEALIX_CLAUDE_SELF_REVIEW || 'on').toLowerCase();
  if (envFlag === 'off') {
    return { ran: false, flagged: [], quarantined: [], reason: 'disabled_env' };
  }
  // Skip review when the run fell back to template-only generation —
  // there's no AI-generated drift to review.
  if (fallbackUsed) {
    return { ran: false, flagged: [], quarantined: [], reason: 'fallback_used' };
  }
  if (!projectPath) return { ran: false, flagged: [], quarantined: [], reason: 'missing_project_path' };

  const dir = generatedDir || path.join(projectPath, 'tests', 'generated');
  if (!fs.existsSync(dir)) return { ran: false, flagged: [], quarantined: [], reason: 'no_generated_dir' };

  const specFiles = fs.readdirSync(dir)
    .filter((n) => SPEC_FILE_RE.test(n))
    .filter((n) => !/healix-qa-contracts/.test(n))
    .slice(0, MAX_SPECS_PER_REVIEW);
  if (specFiles.length === 0) return { ran: false, flagged: [], quarantined: [], reason: 'no_specs' };

  const blocks = [];
  for (const name of specFiles) {
    const abs = path.join(dir, name);
    let content;
    try { content = fs.readFileSync(abs, 'utf8'); } catch { continue; }
    if (typeof content !== 'string' || !content.trim()) continue;
    const truncatedSpec = content.length > MAX_SPEC_BYTES
      ? `${content.slice(0, MAX_SPEC_BYTES)}\n/* ...truncated... */`
      : content;
    const srcRefs = Array.from(content.matchAll(/\[SRC:([^\]\s]+)\]/g)).map((m) => m[1]);
    const srcBlocks = [];
    for (const ref of Array.from(new Set(srcRefs)).slice(0, 4)) {
      const srcAbs = resolveSrcRef(projectPath, ref);
      if (!srcAbs) continue;
      try {
        const srcContent = fs.readFileSync(srcAbs, 'utf8');
        srcBlocks.push(`### ${ref}\n\n\`\`\`\n${srcContent.slice(0, MAX_SRC_BYTES)}${srcContent.length > MAX_SRC_BYTES ? '\n/* ...truncated... */' : ''}\n\`\`\``);
      } catch { /* missing source file is itself an issue, the reviewer will see no SRC content */ }
    }
    blocks.push(`## ${name}\n\n\`\`\`ts\n${truncatedSpec}\n\`\`\`\n\n${srcBlocks.join('\n\n') || '_(no cited sources)_'}`);
  }

  const prompt = `Review each spec below. Output JSON array per the system prompt — no other text.\n\n${blocks.join('\n\n---\n\n')}`;

  try {
    const { resultPromise } = spawnClaude({
      prompt,
      projectPath,
      binary,
      model: model || 'claude-haiku-4-5',
      effort: 'low',
      systemPrompt: REVIEW_SYSTEM_PROMPT,
    });
    const result = await resultPromise;
    const summary = String(result?.summary || '').trim();
    const flagged = parseReviewerJson(summary);
    if (!Array.isArray(flagged)) {
      Logger.warn('ClaudeLocal/Review', 'reviewer did not return JSON array', { sample: summary.slice(0, 200) });
      return { ran: true, flagged: [], quarantined: [], reason: 'reviewer_bad_output' };
    }
    const quarantined = [];
    for (const f of flagged) {
      if (!f || !f.file || !f.severity) continue;
      if (String(f.severity).toLowerCase() !== 'high') continue;
      const target = specFiles.find((n) => n === f.file || path.basename(f.file) === n);
      if (!target) continue;
      const absSpec = path.join(dir, target);
      if (quarantineSpec({ abs: absSpec, runId, projectPath, reason: 'g54_self_review_high', issue: f.issue })) {
        quarantined.push({ file: target, severity: 'high', issue: f.issue });
      }
    }
    return { ran: true, flagged, quarantined };
  } catch (err) {
    Logger.warn('ClaudeLocal/Review', 'review pass threw', { reason: err?.message });
    return { ran: false, flagged: [], quarantined: [], reason: `error:${err?.message || 'unknown'}` };
  }
}

function parseReviewerJson(text) {
  if (!text) return null;
  // Tolerant: try direct JSON, then markdown-fenced JSON.
  try { return JSON.parse(text); } catch { /* try fenced */ }
  const fence = text.match(/```(?:json)?\s*(\[[\s\S]*?\])\s*```/);
  if (fence) {
    try { return JSON.parse(fence[1]); } catch { /* fall through */ }
  }
  // Try to find a bare `[...]` body.
  const bare = text.match(/(\[[\s\S]*\])/);
  if (bare) {
    try { return JSON.parse(bare[1]); } catch { /* fall through */ }
  }
  return null;
}

function resolveSrcRef(projectPath, ref) {
  if (!ref) return null;
  // [SRC:foo.ts] — typically a project-relative path.
  const cand = path.isAbsolute(ref) ? ref : path.join(projectPath, ref);
  if (fs.existsSync(cand)) return cand;
  // Drop a leading `./` or `/`, try again.
  const trimmed = ref.replace(/^\.\//, '').replace(/^\//, '');
  const cand2 = path.join(projectPath, trimmed);
  if (fs.existsSync(cand2)) return cand2;
  return null;
}

function quarantineSpec({ abs, runId, projectPath, reason, issue }) {
  try {
    const quarantineDir = path.join(projectPath, '.healix', 'quarantined', runId || 'unknown', 'g54-self-review');
    fs.mkdirSync(quarantineDir, { recursive: true });
    const dest = path.join(quarantineDir, path.basename(abs));
    fs.renameSync(abs, dest);
    fs.writeFileSync(`${dest}.reason.json`, JSON.stringify({ reason, issue, at: new Date().toISOString() }, null, 2));
    return true;
  } catch {
    return false;
  }
}

module.exports = {
  runSelfReviewPass,
  // exported for testing
  _internals: {
    parseReviewerJson,
    resolveSrcRef,
  },
};
