// Generated by Healix for pre-run validation only.
// It intentionally does not modify or depend on the user's Playwright config.
module.exports = {
  testDir: "/Users/krishsharma/Desktop/Healix/TestBot_MCP/compat-fixtures/pulseboard-planted-bugs/tests/generated",
  testMatch: [new RegExp("\\.(?:spec|test)\\.(?:ts|js|mts|mjs|cts|cjs)$")],
  timeout: 60000,
  fullyParallel: false,
  forbidOnly: false,
  retries: 0,
  workers: 1,
  reporter: [['list']],
  use: {
    baseURL: process.env.HEALIX_TARGET_BASE_URL || process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:3000',
    trace: 'off',
    screenshot: 'off',
    video: 'off',
  },
};
